### ISSUE TITLE
lpeg 1.0.1

### ISSUE THREAD

**Issue by chcg** [dail8859/ScintilluaPlusPlus#3]
See http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.0.1.tar.gz

Version 1.0.1 is available. Documentation of the changes seems to not exist. Build with this version seems to be ok. 

From test.lua:

-- bug in 1.0: failed match-time that used previous match-time results
-- bug in 1.0: problems with math-times returning too many captures

Would you like to receive a PR on this?

**Comment by dail8859** [comment]
Sure. From the sounds of it, this is just a minor bug fix release so updating is probably wise and won't introduce any new problems.

**Comment by dail8859** [comment]
Closed by #4
