### ISSUE TITLE
need help to create a new lexer

### ISSUE THREAD

**Issue by MaDill** [dail8859/ScintilluaPlusPlus#6]
Hi,

I try to create a new lexer for Denso robots. The source files are recognized as "densopacscript (lpeg)", but nothing is highlighted or folded. Attached is the ini, the lua file and a sample sourcecode file. Can you give me some hints what I made wrong?

[ScintilluaPlusPlusDenso.zip](https://github.com/dail8859/ScintilluaPlusPlus/files/854641/ScintilluaPlusPlusDenso.zip)

Thank you very much.

**Comment by dail8859** [comment]
Hi. Glad to see you are putting it to use :)

Let me first say I'm no expert when it comes to writing these lexers...as I've never actually written one myself. All these were preexisting from the Scintillua project.

However I did look through it and saw this:

```lua
-- Macros.
local macros = token('macro_style', '__' * word_match({
  'VERTICAL_ROBOT', 'SCARA_ROBOT', 'VERSION', 'VRC', 'RC8', 'NAME', 'FILE',
  'PATH', 'SIMULATION'
} * '__', nil, true))
```

And verified that this was causing the issue, though I'm not sure *why* exactly. If I comment out these lines and remove the other couple of references to `macros` it works. 

I did notice the `autoit.lua` file also uses something very similar to this for macros, so that might be something worth looking into further.

**Comment by dail8859** [comment]
I managed to hack in a bit of debugging code and got this Lua error:

> "densopacscript.lua:276: attempt to perform arithmetic on a table value"

I think the code section I posted needs to be changed to this:

```lua
-- Macros.
local macros = token('macro_style', '__' * word_match({
  'VERTICAL_ROBOT', 'SCARA_ROBOT', 'VERSION', 'VRC', 'RC8', 'NAME', 'FILE',
  'PATH', 'SIMULATION'
}, nil, true) * '__')
```

This allows it to parse the file though the macros don't seem to be recognized at all...but that might be related to something else.

**Comment by nbred5** [comment]
The only way I could get it too work was as follows:

```lua
local macro1 = P('__') * word_match({
  'VERTICAL_ROBOT__', 'SCARA_ROBOT__', 'VERSION__', 'VRC__', 'RC8__', 'NAME__', 'FILE__',
  'PATH__', 'SIMULATION__'
}, '', true)


local macro = token('macro', macro1)

M._rules = {
  {'whitespace', ws},
  {'comment', comments},
  {'macro', macro},
  {'keyword', keywords},
  {'string', strings},
  {'number', numbers},
  {'preproc', preprocessor},
  {'variable', variables},
  --{'identifier', identifiers},
  {'operator', operators}
}

M._tokenstyles = {
  macro = l.STYLE_PREPROCESSOR
}

```

**Comment by dail8859** [comment]
@nbred5 Yeah I came to the same conclusion. It seems that any alphanumeric or underscore characters following `word_match()` are not working (for example using `##` instead of `__` works fine). I sent an email to the Scintillua mailing list to see if this is a bug or limitation.

**Comment by MaDill** [comment]
Thank you for your help. The highlighting is working now. But with the folding I'm still not happy. When you have time it would be great if  you can give me some more hints. I use version 1.0.1

[ScintilluaPlusPlusDenso.zip](https://github.com/dail8859/ScintilluaPlusPlus/files/857745/ScintilluaPlusPlusDenso.zip)

Another question is, how can I make a syntax check if the lua file. Where did you see the errors? I run notepad++ from the terminal, but also not get messages there. If i run it with the LuaScript plugin I receive these errors:
`File:4: module 'lexer' not found:
	no field package.preload['lexer']
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\lua\lexer.lua'
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\lua\lexer\init.lua'
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\lexer.lua'
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\lexer\init.lua'
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\..\share\lua\5.3\lexer.lua'
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\..\share\lua\5.3\lexer\init.lua'
	no file '.\lexer.lua'
	no file '.\lexer\init.lua'
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\lexer.dll'
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\..\lib\lua\5.3\lexer.dll'
	no file 'C:\Users\madill\Downloads\_PortablePrograms\Notepad++\loadall.dll'
	no file '.\lexer.dll'
`

**Comment by dail8859** [comment]
> it would be great if you can give me some more hints

I'll see what I can do.

> If i run it with the LuaScript plugin I receive these errors

Just to be clear this works completely independently from LuaScript. If you mess around with the `package.path` lua variable you could make it find the `lexer` module but that would just run into another error that it would not be able to find the lpeg module.

> Where did you see the errors?

I modified this plugin's code. Since this plugin has its own lua virtual machine there are some was to see if any errors occurred. I hope that sometime in the near future this plugin will report these kinds of errors directly to the user. See #7 

---

Also I got a response from the Scintillua mailing list about the problem with `word_match()`. They recommend not doing this as `word_match()` grabs as much input as possible (think of greedy regular expression matching) and grabs as much input matching [`[%w_]`](https://www.lua.org/manual/5.3/manual.html#6.4.1). So it is best to do as @nbred5 suggested and just put the underscores as part of the word list.

**Comment by dail8859** [comment]
I think part of the difficulty is that this languages requires multiple keywords in sequence and the space between the two keywords are lexed as white space. So it is more complex than most other lexers just looking for an exact match. There might be some other lexers that have to deal with this so those might be good to reference.

Again I am no expert when it comes to Scintillua but I'm assuming you'd have to do something more complex, such as using functions to do some extra logic. The documentation for the [code folding](https://foicica.com/scintillua/api.html#lexer.Code.Folding) shows that you can use functions for some extra text processing. You would probably have to do something like check to see if the keyword `Loop` is in the correct context to fold or not, meaning if `Exit` is before it then it wouldn't need folding, etc.

Unfortunately I probably can't provide any more useful information past this.

**Comment by MaDill** [comment]
OK. Thank you for your support and the plugin. I'm looking for further versions.

**Comment by MaDill** [comment]
Hi,

this is my latest version. I escaped now the "Exit".

What is not working is the fpöding of sequenced comments. I tried the function from lexer.lua but it is not working.
>-- @usage [l.COMMENT] = {['--'] = l.fold_line_comments('--')}
-- @usage [l.COMMENT] = {['//'] = l.fold_line_comments('//')}
-- @name fold_line_comments
function M.fold_line_comments(prefix)


I checked this with some c sourcecode and the predefined ansi_c.lua lexer and there a sequence of // comments are also not folded. Also in lua it is not working in my notepad++. Maybe in this function is still something wrong maybe on my side is something wrong.

But nevertheless, I think I will let it first like it is. Maybe someone can use it. 

[ScintilluaPlusPlusDenso.zip](https://github.com/dail8859/ScintilluaPlusPlus/files/858870/ScintilluaPlusPlusDenso.zip)

**Comment by dail8859** [comment]
@MaDill 

I think this section of the Scintillua manual is why the comment folding isn't working for you.

> If **fold.line.comments** is set to 1, multiple, consecutive, line comments are folded and only the top-level comment is shown. There is a small performance penalty for large source files when this option and folding are enabled. The default is 0.

I think this property would be needed to be set the by the plugin.
