### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by dail8859** [dail8859/ScintilluaPlusPlus#7]
[SCI_GETSTATUS](https://foicica.com/scintillua/api.html#SCI_GETSTATUS) can be used to check for Lua error messages. Possibly check this after `Colourise()` to see if the initial lexing worked.

Also Scintilla recommends checking to make sure setting a lexer actually worked:

> To test if your lexer assignment worked, use SCI_GETLEXER before and after setting the new lexer to see if the lexer number changed.

**Comment by MaDill** [comment]
it would be nice to get the errors or prints in some kind of terminal. This is from the lexer.lua comments:

>-- ### Troubleshooting
>--
>-- Errors in lexers can be tricky to debug. Lexers print Lua errors to
>-- `io.stderr` and `_G.print()` statements to `io.stdout`. Running your editor
>-- from a terminal is the easiest way to see errors as they occur.
