### ISSUE TITLE
colorization is lost when file is changed extern

### ISSUE THREAD

**Issue by MaDill** [dail8859/ScintilluaPlusPlus#8]
When the file is changed by another program and notepad++ detect the change, the colorization is lost. Also edit the file in notepad++ will not bring back the colors. A tab change to another file in notepad++ and change back bring also the colors back.

**Comment by dail8859** [comment]
I ran into this as well. Unfortunately Notepad++ does not provide any type of notification to the plugin that a file has been reloaded. For now your best option is to just switch to another file and then back.

This is still something I would like to have fixed in the future though.

**Comment by MaDill** [comment]
It looks like this is somehow "fixed" with N++ 7.4 (32bit). With N++7.3.3 (32bit) the colorization is lost, with 7.4 everything is colored in the right way. I didn't test the 64bit version. Installed is Scintillua++ 1.1. Maybe you can confirm this with the N++ source code and then close this issue.

**Comment by dail8859** [comment]
Some quick initial testing with v7.4 confirms that this is somehow fixed. I'll keep this open for now because I want to dig into this further and figure out *why* it is fixed. Thanks.

**Comment by dail8859** [comment]
Looks like https://github.com/notepad-plus-plus/notepad-plus-plus/commit/336992ea77389255eb14759880cfb4e1a88ea2f6 did the trick. It was originally meant to fix another issue with N++ not highlighting URLs after a reload. This now causes the `NPPN_BUFFERACTIVATED` message to get fired after a reload, which allows Scintillua++ to relex the file. :+1:
